import Link from 'next/link';
import Image from 'next/image';
import { ArrowUpRight, ArrowRight, Phone, Workflow, MessagesSquare, Bot, PanelsTopLeft, MoveRight } from 'lucide-react';
import { SiteHeader, SiteFooter, AssessmentLink } from './site-components';

const services = [
  { icon: Phone, title: 'AI receptionist', description: 'Answer defined calls, capture intent, qualify enquiries and pass the right ones to your team.', href: '/ai-receptionist', label: 'Explore call handling' },
  { icon: ArrowRight, title: 'Lead follow-up', description: 'Respond to new enquiries, update your CRM and keep follow-up moving on your rules.', href: '/lead-follow-up', label: 'Explore lead follow-up' },
  { icon: Workflow, title: 'Workflow automation', description: 'Connect forms, email, calendars, spreadsheets, databases and the software you already use.', href: '/ai-automation', label: 'Explore automation' },
  { icon: MessagesSquare, title: 'Customer support AI', description: 'Answer approved questions and hand complex or sensitive conversations to a person.', href: '/ai-chatbot', label: 'Explore support AI' },
  { icon: Bot, title: 'Focused AI agents', description: 'Give an agent a defined task, approved tools, clear limits and a human handoff.', href: '/ai-agents', label: 'Explore AI agents' },
  { icon: PanelsTopLeft, title: 'Custom business systems', description: 'Build an API, dashboard or app when your workflow needs more than a no-code tool.', href: '/custom-ai-systems', label: 'Explore custom systems' },
];
const problems = [
  ['01', 'A lead lands in an inbox', 'A reply waits until someone is free.'],
  ['02', 'A call goes unanswered', 'The customer tries the next business.'],
  ['03', 'Someone copies the details', 'The same information enters three tools.'],
  ['04', 'The follow-up is forgotten', 'Good enquiries go quiet without a next step.'],
];

export default function Home() {
  return <><SiteHeader/><main>
    <section className="hero wrap"><div className="hero-copy">
      <p className="eyebrow"><span className="eyebrow-line"/> AI AUTOMATION FOR REAL BUSINESS WORK</p>
      <h1>Stop paying people to do work <em>software can do.</em></h1>
      <p className="hero-lede">I design and build systems that answer calls, follow up with leads, handle routine questions and move information between the tools your business already uses.</p>
      <div className="hero-actions"><AssessmentLink>Find my automation opportunities <ArrowUpRight size={18}/></AssessmentLink><a className="text-link" href="#how-it-works">See how it works <ArrowRight size={17}/></a></div>
      <p className="micro">A short assessment · No obligation · Practical recommendations</p>
      <div className="founder-note"><span className="founder-mark">ASM</span><span><strong>Abdullah Sher Muhammad</strong><small>Software engineer · Founder, Devisgon</small></span></div>
    </div><div className="hero-visual"><div className="hero-visual-heading"><span>DEVISGON / AI SYSTEMS</span><span>01 — 04</span></div><Image className="hero-person" src="/images/executive-editorial-cutout.png" alt="Illustrative portrait of a business leader in a charcoal suit" width={1024} height={1536} priority unoptimized/><div className="hero-visual-footer"><span>THOUGHTFUL SYSTEMS.<br/>DECISIVE EXECUTION.</span><span className="illustration-label">Illustrative portrait</span></div></div></section>
    <section className="problem-section" id="problems"><div className="wrap"><div className="section-intro"><p className="eyebrow">THE EVERYDAY BOTTLENECK</p><h2>Work keeps moving. <em>Your systems don’t.</em></h2><p>Most teams already have enough software. The expensive part is what happens in the gaps between their tools.</p></div><div className="problem-grid">{problems.map(([n,title,detail])=><div className="problem-item" key={n}><span>{n}</span><h3>{title}</h3><p>{detail}</p></div>)}</div><div className="section-tail">The goal is a clear next step for every lead, call and customer request. <Link href="/assessment">Find where to start <ArrowUpRight size={16}/></Link></div></div></section>
    <section className="services-section wrap" id="solutions"><div className="section-intro compact"><p className="eyebrow">WHAT I BUILD</p><h2>Pick the problem.<br/><em>I’ll build around it.</em></h2><p>Start with one workflow. Make it reliable. Expand when it earns its place.</p></div><div className="service-grid">{services.map(({icon:Icon,title,description,href,label},i)=><Link href={href} className="service-card" key={title}><div className="service-top"><span className="service-icon"><Icon size={23} strokeWidth={1.65}/></span><span className="service-number">0{i+1}</span></div><div><h3>{title}</h3><p>{description}</p></div><span className="service-link">{label} <ArrowUpRight size={17}/></span></Link>)}</div></section>
    <section className="mechanism-section" id="how-it-works"><div className="wrap mechanism-grid"><div><p className="eyebrow light">THE METHOD</p><h2>AI is one piece.<br/><em>The workflow is the system.</em></h2><p>I map what starts the process, where information lives, what gets decided, what action follows and where a person takes over. Then I build and test the smallest useful version.</p><Link className="button light-button" href="/about">How I work <ArrowUpRight size={18}/></Link></div><div className="mechanism-list">{['Trigger','Context','Decision','Action','Human handoff'].map((item,i)=><div key={item}><span>0{i+1}</span><strong>{item}</strong><MoveRight size={19}/></div>)}</div></div></section>
    <section className="use-case wrap"><div className="section-intro"><p className="eyebrow">A SAMPLE WORKFLOW</p><h2>What changes after<br/><em>the lead comes in?</em></h2></div><div className="comparison"><div><span className="comparison-label">TODAY</span><h3>A new enquiry arrives.</h3><p>Someone sees it later, copies details into the CRM, sends a response and tries to remember the next follow-up.</p><div className="comparison-foot">Inbox → Person → CRM → Calendar</div></div><div className="comparison-after"><span className="comparison-label">WITH A CONNECTED WORKFLOW</span><h3>The next step is already moving.</h3><p>The enquiry is captured, classified against your rules, logged, answered and routed to the right person when needed.</p><div className="comparison-foot">Enquiry → Rules + AI → CRM + Response + Handoff</div></div></div><p className="sample-disclaimer">Illustrative workflow. The actual steps and tools are defined around your business.</p></section>
    <section className="people-feature"><div className="wrap people-feature-grid"><div className="people-feature-image"><Image src="/images/strategist-editorial-cutout.png" alt="Illustrative portrait of a strategist working at a laptop" width={1024} height={1536} unoptimized/><span>Illustrative portrait</span></div><div><p className="eyebrow">HUMANS IN THE LOOP</p><h2>Give your team time for the work <em>that needs them.</em></h2><p>The system can take on the repetitive steps. Your people keep ownership of exceptions, relationships and decisions that need judgment.</p><Link className="inline-link" href="/ai-automation">See what can be automated <ArrowUpRight size={18}/></Link></div></div></section><section className="about-preview"><div className="wrap about-preview-grid"><div className="about-monogram" aria-hidden="true"><span>ASM</span><small>BUILD THE WORKFLOW.</small></div><div><p className="eyebrow">THE PERSON BEHIND THE SYSTEM</p><h2>Engineering depth.<br/><em>Business-first thinking.</em></h2><p>I’m Abdullah Sher Muhammad, a software engineer and the founder of Devisgon. I work across APIs, web applications, cloud infrastructure and automation, so a solution can go beyond a prompt or a disconnected tool.</p><div className="skill-line"><span>n8n</span><span>APIs</span><span>Next.js</span><span>Node.js</span><span>FastAPI</span><span>AWS</span></div><Link className="inline-link" href="/about">Meet Abdullah <ArrowUpRight size={18}/></Link></div></div></section>
    <section className="process-section wrap"><div className="section-intro compact"><p className="eyebrow">THE FIRST STEP</p><h2>One process.<br/><em>A practical plan.</em></h2></div><div className="process-grid"><div><span>01 / UNDERSTAND</span><h3>Show me the bottleneck.</h3><p>Tell me where enquiries, calls, support requests or information currently get stuck.</p></div><div><span>02 / DESIGN</span><h3>Map the first workflow.</h3><p>We define the trigger, tools, rules, exceptions and what your team should still own.</p></div><div><span>03 / BUILD</span><h3>Start small and test.</h3><p>Build a contained version, check edge cases, document it and decide what deserves expansion.</p></div></div></section>
    <section className="final-cta"><div className="wrap final-cta-inner"><div><p className="eyebrow light">FREE AI OPPORTUNITY ASSESSMENT</p><h2>What is your team still doing <em>manually?</em></h2><p>Tell me about one slow process and the tools involved. I’ll look for a sensible place to start.</p></div><div><AssessmentLink light>Find my automation opportunities <ArrowUpRight size={18}/></AssessmentLink><small>No credit card · No obligation</small><Link className="final-secondary" href="/book-call">Request a 15-minute review →</Link></div></div></section>
  </main><SiteFooter/></>;
}
