export const projectCategories = [
  { id: 'automations', title: 'Automations', description: 'Repeatable business operations across sales, support, hiring, finance and reporting.' },
  { id: 'ai-automations', title: 'AI Automations', description: 'Assistants and workflows that use AI for conversation, content or ticket handling.' },
  { id: 'scraping', title: 'Scraping', description: 'Public-data extraction and structured research or reporting workflows.' },
  { id: 'integrations', title: 'Integrations', description: 'Workflows that move records and notifications between business applications.' },
  { id: 'webhooks', title: 'Webhooks', description: 'Event and HTTP-based connections between spreadsheets, invoicing and custom software.' },
  { id: 'solution-architecture', title: 'Solution Architecture', description: 'Business process analysis and a documented automation roadmap.' },
  { id: 'websites', title: 'Websites', description: 'Business, product and agency websites with content, lead generation or CMS features.' },
  { id: 'web-apps', title: 'Web Apps', description: 'Interactive full-stack applications, dashboards and SaaS platforms.' },
] as const;

export type ProjectCategory = (typeof projectCategories)[number]['id'];

export type Project = {
  slug: string;
  title: string;
  shortTitle: string;
  category: ProjectCategory;
  summary: string;
  context: string;
  workflow: [string, string, string];
  stack: string[];
  note?: string;
};

// Source order retains Abdullah's original 22 projects followed by two sets of additions. Workflows describe scope and
// visible/documented connections; they do not imply measured outcomes.
export const projects: Project[] = [
  {
    slug: 'google-workspace-contractor-hiring',
    title: 'Google Workspace Job Posting, Trade-Agent Bidding & Contractor Hiring Automation System',
    shortTitle: 'Google Workspace Contractor Hiring Automation',
    category: 'automations',
    summary: 'A Google Workspace workflow for coordinating job postings, trade-agent bids and contractor hiring steps.',
    context: 'The project brings the steps of contractor recruitment into a connected Google Workspace process so job information, bids and hiring activity can be handled together.',
    workflow: ['Prepare and share job postings through the Google Workspace process.', 'Collect and organize trade-agent bids against the relevant opportunity.', 'Carry the selected contractor information into the hiring workflow.'],
    stack: ['Google Workspace', 'Business process automation'],
  },
  {
    slug: 'ai-agent-crm-slack-notion-zapier',
    title: 'AI Agent CRM Integration — Zapier-Powered Slack, Notion & AI Workflow Automation',
    shortTitle: 'AI Agent CRM Integration with Slack and Notion',
    category: 'ai-automations',
    summary: 'Connects CRM work with Slack and Notion through Zapier and an AI-assisted workflow.',
    context: 'This project combines CRM activity, team communication and a shared information workspace in one AI-assisted integration.',
    workflow: ['Use CRM activity as context for the automation.', 'Coordinate actions across Zapier, Slack and Notion.', 'Bring AI processing into the connected workflow where it is useful.'],
    stack: ['Zapier', 'CRM', 'Slack', 'Notion', 'AI agent'],
  },
  {
    slug: 'telegram-ai-voice-assistant',
    title: 'Telegram AI Voice Assistant — n8n, OpenAI & Custom Text-to-Speech Automation',
    shortTitle: 'Telegram AI Voice Assistant',
    category: 'ai-automations',
    summary: 'A Telegram assistant workflow that combines OpenAI responses with custom text-to-speech output.',
    context: 'The assistant links a Telegram conversation to an n8n workflow, AI response generation and a voice-output step.',
    workflow: ['Receive an interaction through Telegram.', 'Process the request with n8n and OpenAI.', 'Produce a spoken response through the custom text-to-speech step.'],
    stack: ['Telegram', 'n8n', 'OpenAI', 'Text-to-speech'],
  },
  {
    slug: 'meta-ads-ai-marketing-automation',
    title: 'Meta Ads AI Marketing Automation — n8n-Powered Ad Creative Generation & Facebook Campaign Publishing',
    shortTitle: 'Meta Ads AI Marketing Automation',
    category: 'ai-automations',
    summary: 'An n8n workflow for AI-assisted ad creative generation and Facebook campaign publishing.',
    context: 'This marketing workflow joins creative generation and the campaign publishing process through n8n.',
    workflow: ['Prepare the campaign inputs for creative generation.', 'Use AI in the n8n workflow to produce ad creative material.', 'Carry the approved material into the Facebook campaign publishing flow.'],
    stack: ['n8n', 'Meta Ads', 'Facebook', 'AI'],
  },
  {
    slug: 'ai-voice-meeting-assistant',
    title: 'AI Voice Meeting Assistant — Conversational Meeting Scheduling & Calendly Automation',
    shortTitle: 'AI Voice Meeting Assistant',
    category: 'ai-automations',
    summary: 'A conversational voice workflow for arranging meetings through Calendly.',
    context: 'The assistant explores how a voice conversation can lead into a structured meeting scheduling process.',
    workflow: ['Handle the scheduling conversation through the voice assistant.', 'Capture the meeting request and relevant scheduling details.', 'Connect the request to Calendly for an available booking step.'],
    stack: ['AI voice', 'Calendly', 'Scheduling automation'],
  },
  {
    slug: 'google-sheets-clay-apps-script-webhook',
    title: 'Google Sheets-to-Clay Data Synchronization — Google Apps Script & Webhook Automation',
    shortTitle: 'Google Sheets to Clay with Apps Script and Webhooks',
    category: 'webhooks',
    summary: 'Synchronizes spreadsheet records with Clay through an Apps Script and webhook workflow.',
    context: 'This is the Google Apps Script implementation of the Sheets-to-Clay connection; a separate project below uses Make and HTTP automation.',
    workflow: ['Read or prepare data in Google Sheets.', 'Use Apps Script to format and send the relevant record through a webhook.', 'Pass the data to the Clay table workflow.'],
    stack: ['Google Sheets', 'Google Apps Script', 'Clay', 'Webhooks'],
  },
  {
    slug: 'gohighlevel-lead-generation-sales',
    title: 'GoHighLevel Lead Generation & Sales Automation — LinkedIn Outreach, CRM Pipelines, Appointment Scheduling & Email Workflows',
    shortTitle: 'GoHighLevel Lead Generation and Sales Automation',
    category: 'automations',
    summary: 'Brings outreach, lead pipeline stages, appointments and follow-up email into a GoHighLevel sales workflow.',
    context: 'The project connects lead generation activity to CRM pipeline management and the subsequent scheduling and email steps.',
    workflow: ['Bring LinkedIn outreach activity into the lead-generation process.', 'Organize leads and stages in GoHighLevel CRM pipelines.', 'Coordinate appointment scheduling and email follow-up.'],
    stack: ['GoHighLevel', 'LinkedIn', 'CRM pipelines', 'Email automation'],
  },
  {
    slug: 'youtube-liked-videos-ifttt-sheets',
    title: 'YouTube Liked Video Tracking Automation — IFTTT & Google Sheets Data Logging',
    shortTitle: 'YouTube Liked Video Tracking with IFTTT',
    category: 'automations',
    summary: 'Logs liked YouTube videos to Google Sheets with an IFTTT automation.',
    context: 'A small personal-data logging workflow replaces manual copying of liked-video information into a spreadsheet.',
    workflow: ['Use a liked YouTube video as the automation event.', 'Pass the event information through IFTTT.', 'Record the video information in Google Sheets.'],
    stack: ['IFTTT', 'YouTube', 'Google Sheets'],
  },
  {
    slug: 'facebook-content-marketing-make',
    title: 'Facebook Content Marketing Automation — Make.com, Google Sheets, Mailchimp & Google Calendar Integration',
    shortTitle: 'Facebook Content Marketing Automation',
    category: 'automations',
    summary: 'Coordinates Facebook content planning and email marketing data across Sheets, Mailchimp and Calendar.',
    context: 'The workflow brings together content inputs, scheduling information and email marketing tools rather than managing each step in isolation.',
    workflow: ['Organize campaign or content information in Google Sheets.', 'Use Make to connect Facebook-related activity with Google Calendar.', 'Coordinate the connected email-marketing step in Mailchimp.'],
    stack: ['Make', 'Facebook', 'Google Sheets', 'Mailchimp', 'Google Calendar'],
  },
  {
    slug: 'hotel-booking-operations-make',
    title: 'Hotel Booking Operations Automation — Make.com, Jotform, Airtable, Google Sheets, Asana & ActiveCampaign',
    shortTitle: 'Hotel Booking Operations Automation',
    category: 'automations',
    summary: 'Connects booking form intake with records, task management and email follow-up tools.',
    context: 'Hotel booking information passes between the intake form, operational records, team tasks and marketing or guest communication tools.',
    workflow: ['Collect booking details through Jotform.', 'Organize the data in Airtable and Google Sheets with Make.', 'Connect operational tasks in Asana and communication steps in ActiveCampaign.'],
    stack: ['Make', 'Jotform', 'Airtable', 'Google Sheets', 'Asana', 'ActiveCampaign'],
  },
  {
    slug: 'google-sheets-clay-make-http',
    title: 'Google Sheets-to-Clay Lead Data Integration — Make.com & HTTP Automation',
    shortTitle: 'Google Sheets to Clay with Make and HTTP',
    category: 'integrations',
    summary: 'A separate Sheets-to-Clay lead data workflow built with Make and HTTP requests.',
    context: 'This implementation uses Make and HTTP automation for the Sheets-to-Clay connection, distinct from the Apps Script and webhook project.',
    workflow: ['Take lead data from Google Sheets.', 'Use Make to prepare and send the data through an HTTP step.', 'Connect the result with the Clay table workflow.'],
    stack: ['Make', 'HTTP', 'Google Sheets', 'Clay'],
  },
  {
    slug: 'it-ticket-notifications-make-twilio',
    title: 'IT Support Ticket Notification Automation — Make.com, monday.com, Airtable & Twilio',
    shortTitle: 'IT Ticket Notifications with Make and Twilio',
    category: 'integrations',
    summary: 'Links IT ticket records and status information with automated notifications.',
    context: 'The project connects work tracking and ticket data with an outbound notification channel for support operations.',
    workflow: ['Use monday.com and Airtable for ticket-related information.', 'Connect the records and workflow steps through Make.', 'Send the related notification through Twilio.'],
    stack: ['Make', 'monday.com', 'Airtable', 'Twilio'],
  },
  {
    slug: 'hubspot-contact-gmail-n8n',
    title: 'HubSpot Contact Management & Gmail Notification Automation — n8n, Jotform & Google Sheets Integration',
    shortTitle: 'HubSpot Contact Management and Gmail Notifications',
    category: 'integrations',
    summary: 'Moves contact-form information through an n8n and HubSpot workflow with Gmail notifications.',
    context: 'The workflow combines a form submission, structured contact information and an email notification in one connected process.',
    workflow: ['Capture contact information through Jotform.', 'Process the information with n8n, Google Sheets and HubSpot.', 'Send the relevant notification through Gmail.'],
    stack: ['n8n', 'HubSpot', 'Jotform', 'Google Sheets', 'Gmail'],
  },
  {
    slug: 'pdf-invoice-pabbly-google-workspace',
    title: 'Automated PDF Invoice Generation & Email Delivery — Pabbly Connect & Google Workspace Business Process Automation',
    shortTitle: 'PDF Invoice Generation with Pabbly and Google Workspace',
    category: 'automations',
    summary: 'Uses form and document data to prepare PDF invoices and send them by email through a connected Google Workspace process.',
    context: 'This workflow reduces manual copying between intake, document creation, file storage and invoice delivery.',
    workflow: ['Take invoice inputs from Google Forms and the supporting lookup data.', 'Use Pabbly Connect, Google Docs and Drive to prepare and store a PDF invoice.', 'Send the resulting invoice through Gmail.'],
    stack: ['Pabbly Connect', 'Google Forms', 'Google Docs', 'Google Drive', 'Gmail'],
  },
  {
    slug: 'quickbooks-invoice-webhook-platform',
    title: 'QuickBooks Invoice Digitization & Webhook Automation Platform — React, Node.js, MongoDB & AWS S3',
    shortTitle: 'QuickBooks Invoice Webhook Platform',
    category: 'webhooks',
    summary: 'A custom application for moving QuickBooks invoice information into a connected platform through webhooks.',
    context: 'The project combines a React interface, Node.js backend, database and file storage with an invoice event workflow.',
    workflow: ['Receive QuickBooks Enterprise cloud invoice information through a webhook flow.', 'Process and store the invoice data in the Node.js and MongoDB application.', 'Use the React interface and AWS S3-backed file handling in the connected platform.'],
    stack: ['React', 'Node.js', 'MongoDB', 'AWS S3', 'QuickBooks', 'Webhooks'],
  },
  {
    slug: 'slack-response-tracking-zapier',
    title: 'Slack Response Tracking & Google Sheets Automation — Zapier Workflow Integration',
    shortTitle: 'Slack Response Tracking with Zapier',
    category: 'automations',
    summary: 'Tracks Slack responses in Google Sheets using a Zapier workflow.',
    context: 'The project turns response activity in a team communication channel into structured spreadsheet records.',
    workflow: ['Observe the relevant Slack response activity.', 'Use Zapier to carry the response information between apps.', 'Record the tracking data in Google Sheets.'],
    stack: ['Zapier', 'Slack', 'Google Sheets'],
  },
  {
    slug: 'ai-support-tickets-n8n-hubspot',
    title: 'AI-Powered Automated Support Ticket Management — n8n, HubSpot, OpenAI, Notion & Jotform',
    shortTitle: 'AI Support Ticket Management',
    category: 'ai-automations',
    summary: 'Routes support form submissions through an AI-assisted ticket workflow across HubSpot and Notion.',
    context: 'The workflow connects request intake and AI processing with the systems used to track support work and related information.',
    workflow: ['Capture a support request through Jotform.', 'Use n8n and OpenAI within the ticket management workflow.', 'Connect the resulting work to HubSpot and Notion.'],
    stack: ['n8n', 'HubSpot', 'OpenAI', 'Notion', 'Jotform'],
  },
  {
    slug: 'jira-service-management-ticket-automation',
    title: 'Jira Service Management IT Support & Ticket Workflow Automation',
    shortTitle: 'Jira Service Management Ticket Automation',
    category: 'automations',
    summary: 'Automates steps in an IT support ticket workflow using Jira Service Management.',
    context: 'This project focuses on repeatable support-ticket handling within Jira Service Management.',
    workflow: ['Capture or organize incoming IT support tickets.', 'Apply ticket workflow rules in Jira Service Management.', 'Coordinate status changes and the subsequent support steps.'],
    stack: ['Jira Service Management', 'IT support automation'],
  },
  {
    slug: 'twitter-x-profile-scraper-python-selenium',
    title: 'Twitter/X Profile Data Scraping Platform — Python, Selenium & Web Automation',
    shortTitle: 'Twitter/X Profile Scraper with Python and Selenium',
    category: 'scraping',
    summary: 'A web form takes a designation and location, then Python and Selenium gather matching profile information for spreadsheet export.',
    context: 'The demonstrated application provides a search form so a user can look for profiles by professional designation and location without editing the scraper code.',
    workflow: ['Enter a designation and location in the web form.', 'Run the search and browser interaction through Python and Selenium.', 'Extract profile names and URLs into a spreadsheet-compatible output.'],
    stack: ['Python', 'Selenium', 'Twitter/X', 'Spreadsheet export'],
    note: 'The supplied demonstration shows the form, browser automation and Excel-compatible results. It does not establish unrestricted access to the platform.',
  },
  {
    slug: 'linkedin-profile-research-ai-agent',
    title: 'LinkedIn Profile Scraping AI Agent — n8n, OpenAI, Google Sheets & Window Buffer Memory',
    shortTitle: 'LinkedIn Profile Research AI Agent',
    category: 'scraping',
    summary: 'A conversational research agent uses a LinkedIn profiles tool and session memory to handle follow-up requests.',
    context: 'The demonstrated n8n agent combines an OpenAI chat model, a LinkedIn profiles tool and Window Buffer Memory for conversational professional-profile research.',
    workflow: ['Submit a natural-language request to the n8n chat trigger.', 'Let the agent call the profiles tool while keeping the session context in memory.', 'Return the research response and use Google Sheets in the structured-data workflow.'],
    stack: ['n8n', 'OpenAI', 'LinkedIn profiles tool', 'Google Sheets', 'Window Buffer Memory'],
    note: 'The supplied recording does not establish direct LinkedIn API integration, automated outreach or extraction of private contact information.',
  },
  {
    slug: 'square-dashboard-retail-automation',
    title: 'Square Dashboard Inventory, Purchase Order & Sales Automation — Python, Google Apps Script & Google Sheets',
    shortTitle: 'Square Inventory, Purchase Order and Sales Automation',
    category: 'automations',
    summary: 'Coordinates Square catalog exports, purchase-order status processing and sales reports with Python and spreadsheet automation.',
    context: 'The documented system uses Python scripts for Square browser and file operations, with Google Apps Script handling spreadsheet-native transformations.',
    workflow: ['Export and process Square catalog information for Google Sheets.', 'Check purchase-order states and move completed records into historical sheets.', 'Export Square sales details for a selected period and refresh reporting sheets.'],
    stack: ['Square Dashboard', 'Python', 'Google Apps Script', 'Google Sheets', 'CSV'],
    note: 'The supplied documentation describes browser, file and spreadsheet automation; it does not establish a Square API integration or real-time synchronization.',
  },
  {
    slug: 'hcpa-pipedrive-automation-architecture',
    title: 'HCPA Business Process Automation & Pipedrive CRM Architecture — Pipedrive, Zapier, Make.com, Google Ads, Meta & Marketing Automation',
    shortTitle: 'HCPA Pipedrive CRM and Automation Architecture',
    category: 'solution-architecture',
    summary: 'A cross-department process review and Pipedrive-centered automation roadmap covering sales, marketing and operations.',
    context: 'The work analyzed existing processes and mapped opportunities to connect lead management, marketing, documents, reporting and finance around Pipedrive.',
    workflow: ['Review operational workflows and identify repetitive work or handoff gaps.', 'Design a Pipedrive-centered CRM structure with pipelines, fields and workflow triggers.', 'Document a roadmap for potential Zapier, Make, advertising, reporting and finance integrations.'],
    stack: ['Pipedrive', 'Zapier', 'Make', 'Google Ads', 'Meta', 'CRM architecture'],
    note: 'This is business process analysis and solution architecture. The source document proposes many integrations; it does not establish that every proposed connection was deployed.',
  },
  {
    slug: 'ohana-financial-management-dashboard',
    title: 'Ohana Financial Management Dashboard',
    shortTitle: 'Ohana Financial Management Dashboard',
    category: 'web-apps',
    summary: 'A financial management dashboard with a React frontend and Node.js backend.',
    context: 'Ohana is a full-stack dashboard project centered on presenting and working with financial information through a web interface.',
    workflow: ['Present financial information in dashboard views.', 'Handle the application interactions in the React frontend.', 'Connect those interactions with Node.js backend services.'],
    stack: ['React', 'Node.js', 'JavaScript', 'Dashboard development'],
  },
  {
    slug: 'full-stack-ecommerce-web-app',
    title: 'Full-Stack E-Commerce Web Application',
    shortTitle: 'Full-Stack E-Commerce Web Application',
    category: 'web-apps',
    summary: 'A full-stack web application for an e-commerce experience.',
    context: 'This project brings the customer-facing commerce interface and its supporting application logic together in a web application.',
    workflow: ['Present an e-commerce interface to the visitor.', 'Handle shopping interactions through the application.', 'Connect the frontend with the supporting backend logic.'],
    stack: ['Full-stack web development', 'E-commerce application'],
  },
  {
    slug: 'google-apps-script-marketing-analytics',
    title: 'Google Apps Script Marketing & Analytics Automation',
    shortTitle: 'Google Apps Script Marketing and Analytics Automation',
    category: 'automations',
    summary: 'Google Apps Script automation for marketing information and analytics workflows.',
    context: 'The project uses Google Apps Script to reduce manual steps in a marketing and analytics process.',
    workflow: ['Gather the relevant marketing or analytics inputs.', 'Run the repeatable processing steps in Google Apps Script.', 'Organize the resulting information for review and reporting.'],
    stack: ['Google Apps Script', 'Marketing automation', 'Analytics'],
  },
  {
    slug: 'osha-government-data-scraping',
    title: 'OSHA Government Data Scraping & Automated Reporting System',
    shortTitle: 'OSHA Government Data Scraping and Reporting',
    category: 'scraping',
    summary: 'A data extraction and reporting workflow for OSHA government information.',
    context: 'The project focuses on collecting relevant public government records and shaping them into a reportable dataset.',
    workflow: ['Identify the OSHA information needed for a report.', 'Extract and structure the relevant records.', 'Produce an automated reporting output from the collected data.'],
    stack: ['OSHA data', 'Web scraping', 'Automated reporting'],
  },
  {
    slug: 'perplexity-ai-python-chat-connector',
    title: 'Perplexity AI API Integration & Python Chat Connector',
    shortTitle: 'Perplexity AI Python Chat Connector',
    category: 'integrations',
    summary: 'A Python connector for sending chat requests to the Perplexity AI API.',
    context: 'This integration links a Python chat interface or workflow to an external AI service through its API.',
    workflow: ['Accept a chat request in the Python connector.', 'Send the request to the Perplexity AI API.', 'Return the API response to the calling workflow.'],
    stack: ['Python', 'Perplexity AI API', 'API integration'],
  },
  {
    slug: 'devautox-company-website',
    title: 'DevAutoX — Technology & Automation Company Website',
    shortTitle: 'DevAutoX Technology Company Website',
    category: 'websites',
    summary: 'A company website presenting technology and automation services.',
    context: 'DevAutoX is a business-facing website project focused on communicating the company and its technology or automation work.',
    workflow: ['Introduce the company and its positioning.', 'Present technology and automation service information.', 'Guide visitors toward learning more or making an enquiry.'],
    stack: ['Website development', 'Technology services', 'Automation positioning'],
  },
  {
    slug: 'social-ai-publishing-platform',
    title: 'Social AI — AI-Powered Social Media Automation & Publishing Platform',
    shortTitle: 'Social AI Publishing Platform',
    category: 'web-apps',
    summary: 'A social publishing platform with a modular NestJS backend for connections, approvals, scheduling and automated posting.',
    context: 'The backend supports workspaces, social account connections, content workflows and scheduled publishing; the supplied frontend repository primarily presents the product through its landing website.',
    workflow: ['Connect supported social accounts within a business workspace.', 'Prepare content and route it through review and approval.', 'Schedule or publish approved content through provider-specific integrations.'],
    stack: ['Next.js', 'React', 'TypeScript', 'NestJS', 'Supabase', 'OAuth', 'Scheduled jobs'],
    note: 'The supplied repositories establish the backend publishing infrastructure and a product landing frontend. They do not establish a completed analytics dashboard, social calendar or AI editor interface.',
  },
  {
    slug: 'mian-tipu-farms-website-cms',
    title: 'Mian Tipu Farms — Agricultural Business Website & Content Management Platform',
    shortTitle: 'Mian Tipu Farms Website and CMS',
    category: 'websites',
    summary: 'An agricultural business website with Payload CMS, MongoDB, blog content and media management.',
    context: 'The project pairs a public Next.js site for the farm with an authenticated Payload CMS environment for managing articles and media.',
    workflow: ['Present farming, dairy, machinery and business information on the public site.', 'Manage blog and media content in Payload CMS.', 'Serve the updated content through the Next.js website.'],
    stack: ['Next.js', 'React', 'Payload CMS', 'MongoDB', 'Tailwind CSS', 'REST', 'GraphQL'],
  },
  {
    slug: 'virtualassistant-au-website',
    title: 'VirtualAssistant.com.au — AI Virtual Receptionist & Business Automation Website',
    shortTitle: 'VirtualAssistant.com.au Website',
    category: 'websites',
    summary: 'An Australian AI receptionist marketing website with industry pages, lead forms and search metadata.',
    context: 'The Next.js website presents the receptionist service across product and industry pages and sends sales enquiries through a server-side contact workflow.',
    workflow: ['Guide visitors through product features and industry-specific pages.', 'Capture an enquiry with validated forms.', 'Deliver the enquiry through a Next.js API route and Resend.'],
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Resend', 'SEO metadata', 'Analytics'],
    note: 'This repository is the marketing and lead-generation website. It does not establish the underlying voice AI or telephony engine.',
  },
  {
    slug: 'memyselfi-ai-product-website',
    title: 'MeMyselfI.ai — AI Personal Productivity Platform Website',
    shortTitle: 'MeMyselfI.ai Product Website',
    category: 'websites',
    summary: 'A SaaS product website presenting the AI productivity platform through feature pages, pricing and contact flows.',
    context: 'The website explains the product concept through pages for inbox, voice assistance, calls, calendar, diary, budgeting, health and secure storage.',
    workflow: ['Present the platform and its individual feature areas.', 'Support exploration through responsive navigation, pricing and support pages.', 'Handle contact enquiries through a server-side route using Resend.'],
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Resend'],
    note: 'The supplied repository is the product website and contact workflow. It does not establish the backend implementation of all advertised productivity features.',
  },
  {
    slug: 'qodify-agency-website',
    title: 'Qodify — AI Solutions & Technology Agency Website',
    shortTitle: 'Qodify Technology Agency Website',
    category: 'websites',
    summary: 'A responsive agency website with service pages, project filtering and animated presentation.',
    context: 'The site uses reusable Next.js components and structured content to present an AI and software services company.',
    workflow: ['Introduce the agency and its service areas.', 'Let visitors browse projects and company information.', 'Present contact options in the frontend experience.'],
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'JSON content'],
    note: 'The supplied repository is a frontend agency website. Its contact form is visual only; the code does not establish a working submission backend.',
  },
  {
    slug: 'abdullah-sher-muhammad-portfolio-website',
    title: 'Abdullah Sher Muhammad — Personal Portfolio / Developer Website',
    shortTitle: 'Abdullah Sher Muhammad Portfolio Website',
    category: 'websites',
    summary: 'A personal website presenting software engineering, AI automation services and selected work.',
    context: 'This website brings Abdullah’s background, solutions, industry focus, project pages and enquiry paths into one responsive portfolio.',
    workflow: ['Introduce the developer and the business problems he works on.', 'Help visitors explore services, industries and project case studies.', 'Offer contact and assessment paths for a relevant project enquiry.'],
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'GitHub Pages'],
  },
  {
    slug: 'laforme-pilates-booking-app',
    title: 'LaForme — Pilates Studio Booking & Customer Experience Platform',
    shortTitle: 'LaForme Pilates Booking App',
    category: 'web-apps',
    summary: 'The customer-facing booking application for a Pilates studio platform.',
    context: 'LaForme’s customer application focuses on discovering studio offerings and progressing through a booking journey. It is distinct from the staff back-office platform listed separately.',
    workflow: ['Present Pilates services and class options to customers.', 'Support the customer booking journey in the web application.', 'Connect customer-facing activity with the broader LaForme platform.'],
    stack: ['Customer web application', 'Pilates booking', 'Frontend development'],
    note: 'The attached write-up documents this as the customer-facing application and describes the separate LaForme Back Office in detail. It does not provide a full technical inventory for this repository.',
  },
  {
    slug: 'devisgon-company-website',
    title: 'Devisgon — AI Automation & Software Development Company Website',
    shortTitle: 'Devisgon Company Website',
    category: 'websites',
    summary: 'The Devisgon company website for presenting AI automation and software development services.',
    context: 'The public-facing site organizes the company’s services and content for prospective clients. Its repository uses Next.js and React with a Payload CMS foundation.',
    workflow: ['Present Devisgon’s services and company information.', 'Organize public website content and media through the site architecture.', 'Give prospective clients a route to learn more and make an enquiry.'],
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Payload CMS', 'PostgreSQL'],
  },
  {
    slug: 'pharmasync-pharmacy-platform',
    title: 'PharmaSync — Pharmacy Management & Healthcare Operations Platform',
    shortTitle: 'PharmaSync Pharmacy Management Platform',
    category: 'web-apps',
    summary: 'A web application project focused on pharmacy management and healthcare operations.',
    context: 'PharmaSync is positioned around bringing pharmacy and related operational work into a connected software platform.',
    workflow: ['Organize pharmacy-related information in the application.', 'Support the day-to-day operational workflow.', 'Provide a central interface for the platform’s management tasks.'],
    stack: ['Web application', 'Pharmacy management', 'Healthcare operations'],
    note: 'The supplied title identifies the project and domain; specific modules, technical stack and deployment status were not documented in the attached write-up.',
  },
  {
    slug: 'total-store-retail-management',
    title: 'Total Store — Gas Station / Convenience Store Management Platform',
    shortTitle: 'Total Store Retail Management Platform',
    category: 'web-apps',
    summary: 'A multi-location retail back-office platform spanning inventory, sales, fuel, purchasing and finance workflows.',
    context: 'The Laravel modular monolith brings store-level operations together with reactive Livewire interfaces and MySQL persistence.',
    workflow: ['Manage products, prices, inventory and purchasing across locations.', 'Record sales, register shifts, fuel and other store operations.', 'Support banking, payroll, POS import/export and support workflows within the back office.'],
    stack: ['Laravel', 'PHP', 'Livewire', 'Blade', 'Tailwind CSS', 'MySQL', 'Laravel queues'],
    note: 'The repository includes a POS integration framework with visible manual import/export adapters. It does not establish a production integration with a named commercial POS provider.',
  },
  {
    slug: 'laforme-back-office-platform',
    title: 'LaForme Back Office — Pilates Studio Administration, Booking, Payments & Operations Management Platform',
    shortTitle: 'LaForme Back Office Platform',
    category: 'web-apps',
    summary: 'The staff administration platform for LaForme studios, schedules, bookings, payments and operations.',
    context: 'A Next.js administration frontend and NestJS API provide the internal control plane for the customer-facing LaForme booking experience.',
    workflow: ['Configure studios, classes, staff availability and equipment.', 'Administer bookings, customers, prices and promotions.', 'Manage payment, wallet, loyalty and notification workflows through the backend.'],
    stack: ['Next.js', 'React', 'TypeScript', 'NestJS', 'Supabase PostgreSQL', 'Redis', 'BullMQ', 'KNET', 'MyFatoorah'],
    note: 'This is the implemented back-office application, separate from the customer booking app. No AI functionality was identified in the supplied repository.',
  },
  {
    slug: 'taskera-ai-agent-platform',
    title: 'Taskera AI — Stateful Multi-Agent AI Assistant, RAG, MCP Tools & Task Automation Platform',
    shortTitle: 'Taskera AI Agent Platform',
    category: 'web-apps',
    summary: 'A stateful AI assistant with tool use, document retrieval, OCR, conversation memory and scheduled tasks.',
    context: 'Taskera combines a lightweight web chat frontend with a FastAPI backend using Gemini, LangGraph tool calling, vector retrieval and persisted conversation state.',
    workflow: ['Receive a request or uploaded document in the chat application.', 'Choose tools or retrieve relevant document context for the agent.', 'Return an answer or schedule a supported task while retaining conversation state.'],
    stack: ['Python', 'FastAPI', 'Gemini', 'LangGraph', 'ChromaDB', 'Supabase', 'SQLite', 'Tesseract OCR', 'Vanilla JavaScript'],
    note: 'The project uses an internal MCP-style JSON-RPC tool layer and a Taskera-managed calendar. The source does not establish an external standards-compliant MCP server or Google Calendar synchronization.',
  },
  {
    slug: 'fulixlabs-multi-agent-backend',
    title: 'FulixLabs Backend — Enterprise Multi-Agent AI Assistant, MCP Tool Orchestration, Persistent Memory & Productivity API',
    shortTitle: 'FulixLabs Multi-Agent Backend',
    category: 'ai-automations',
    summary: 'A NestJS backend for supervisor-and-worker AI agents, MCP tools, semantic memory and productivity APIs.',
    context: 'A supervisor plans requests and delegates steps to specialized agents and tool integrations. The supplied repository contains the backend and API layer.',
    workflow: ['Accept a request through the authenticated NestJS API.', 'Create an execution plan and delegate steps to worker agents and MCP tools.', 'Combine tool results into a response and persist relevant memory or task data.'],
    stack: ['NestJS', 'TypeScript', 'Bytez', 'Qwen', 'MCP SDK', 'LanceDB', 'Supabase PostgreSQL', 'Swagger'],
    note: 'This repository is backend-only. The default LLM is Qwen through Bytez; reminder delivery shown in the source writes to the server console rather than email or push.',
  },
  {
    slug: 'memyselfi-ai-productivity-platform',
    title: 'MeMyselfI.ai — AI-Powered Personal Productivity, Unified Communications & Voice Automation Platform',
    shortTitle: 'MeMyselfI.ai Productivity Platform',
    category: 'web-apps',
    summary: 'A multi-service productivity platform combining a web app, AI backend, unified inbox and identity service.',
    context: 'Four repositories together cover the Next.js frontend, FastAPI AI and call-agent service, Express unified-inbox service and Cognito-based authentication. This platform is distinct from the MeMyselfI product website listed under Websites.',
    workflow: ['Bring communications and personal workflows into the web application.', 'Connect AI assistance, document retrieval and voice call automation through the Python service.', 'Coordinate multi-channel inbox and identity workflows through their dedicated services.'],
    stack: ['Next.js', 'React', 'TypeScript', 'FastAPI', 'Python', 'Express', 'OpenAI Agents', 'AWS Cognito', 'DynamoDB', 'Twilio', 'ElevenLabs'],
    note: 'Provider integrations and call-agent components are represented in the supplied code. Production completeness depends on external permissions and credentials; unsupported encryption or family-sharing claims are excluded.',
  },
];

export const projectsBySlug: Record<string, Project> = Object.fromEntries(projects.map(project => [project.slug, project]));
export const projectPath = (slug: string) => `/case-studies/${slug}/`;
