export const projectCategories = [
  { id: 'automations', title: 'Automations', description: 'Repeatable business operations across sales, support, hiring, finance and reporting.' },
  { id: 'ai-automations', title: 'AI Automations', description: 'Assistants and workflows that use AI for conversation, content or ticket handling.' },
  { id: 'data-scraping', title: 'Data Scraping', description: 'Tools for finding and structuring profile information for research.' },
  { id: 'integrations', title: 'Integrations', description: 'Workflows that move records and notifications between business applications.' },
  { id: 'webhooks', title: 'Webhooks', description: 'Event and HTTP-based connections between spreadsheets, invoicing and custom software.' },
  { id: 'solution-architecture', title: 'Solution Architecture', description: 'Business process analysis and a documented automation roadmap.' },
] as const;

export type ProjectCategory = (typeof projectCategories)[number]['id'];

export type Project = {
  slug: string;
  title: string;
  shortTitle: string;
  category: ProjectCategory;
  summary: string;
  context: string;
  workflow: [string, string, string];
  stack: string[];
  note?: string;
};

// Source order matches Abdullah's 22-project list. Workflows describe scope and
// visible/documented connections; they do not imply measured outcomes.
export const projects: Project[] = [
  {
    slug: 'google-workspace-contractor-hiring',
    title: 'Google Workspace Job Posting, Trade-Agent Bidding & Contractor Hiring Automation System',
    shortTitle: 'Google Workspace Contractor Hiring Automation',
    category: 'automations',
    summary: 'A Google Workspace workflow for coordinating job postings, trade-agent bids and contractor hiring steps.',
    context: 'The project brings the steps of contractor recruitment into a connected Google Workspace process so job information, bids and hiring activity can be handled together.',
    workflow: ['Prepare and share job postings through the Google Workspace process.', 'Collect and organize trade-agent bids against the relevant opportunity.', 'Carry the selected contractor information into the hiring workflow.'],
    stack: ['Google Workspace', 'Business process automation'],
  },
  {
    slug: 'ai-agent-crm-slack-notion-zapier',
    title: 'AI Agent CRM Integration — Zapier-Powered Slack, Notion & AI Workflow Automation',
    shortTitle: 'AI Agent CRM Integration with Slack and Notion',
    category: 'ai-automations',
    summary: 'Connects CRM work with Slack and Notion through Zapier and an AI-assisted workflow.',
    context: 'This project combines CRM activity, team communication and a shared information workspace in one AI-assisted integration.',
    workflow: ['Use CRM activity as context for the automation.', 'Coordinate actions across Zapier, Slack and Notion.', 'Bring AI processing into the connected workflow where it is useful.'],
    stack: ['Zapier', 'CRM', 'Slack', 'Notion', 'AI agent'],
  },
  {
    slug: 'telegram-ai-voice-assistant',
    title: 'Telegram AI Voice Assistant — n8n, OpenAI & Custom Text-to-Speech Automation',
    shortTitle: 'Telegram AI Voice Assistant',
    category: 'ai-automations',
    summary: 'A Telegram assistant workflow that combines OpenAI responses with custom text-to-speech output.',
    context: 'The assistant links a Telegram conversation to an n8n workflow, AI response generation and a voice-output step.',
    workflow: ['Receive an interaction through Telegram.', 'Process the request with n8n and OpenAI.', 'Produce a spoken response through the custom text-to-speech step.'],
    stack: ['Telegram', 'n8n', 'OpenAI', 'Text-to-speech'],
  },
  {
    slug: 'meta-ads-ai-marketing-automation',
    title: 'Meta Ads AI Marketing Automation — n8n-Powered Ad Creative Generation & Facebook Campaign Publishing',
    shortTitle: 'Meta Ads AI Marketing Automation',
    category: 'ai-automations',
    summary: 'An n8n workflow for AI-assisted ad creative generation and Facebook campaign publishing.',
    context: 'This marketing workflow joins creative generation and the campaign publishing process through n8n.',
    workflow: ['Prepare the campaign inputs for creative generation.', 'Use AI in the n8n workflow to produce ad creative material.', 'Carry the approved material into the Facebook campaign publishing flow.'],
    stack: ['n8n', 'Meta Ads', 'Facebook', 'AI'],
  },
  {
    slug: 'ai-voice-meeting-assistant',
    title: 'AI Voice Meeting Assistant — Conversational Meeting Scheduling & Calendly Automation',
    shortTitle: 'AI Voice Meeting Assistant',
    category: 'ai-automations',
    summary: 'A conversational voice workflow for arranging meetings through Calendly.',
    context: 'The assistant explores how a voice conversation can lead into a structured meeting scheduling process.',
    workflow: ['Handle the scheduling conversation through the voice assistant.', 'Capture the meeting request and relevant scheduling details.', 'Connect the request to Calendly for an available booking step.'],
    stack: ['AI voice', 'Calendly', 'Scheduling automation'],
  },
  {
    slug: 'google-sheets-clay-apps-script-webhook',
    title: 'Google Sheets-to-Clay Data Synchronization — Google Apps Script & Webhook Automation',
    shortTitle: 'Google Sheets to Clay with Apps Script and Webhooks',
    category: 'webhooks',
    summary: 'Synchronizes spreadsheet records with Clay through an Apps Script and webhook workflow.',
    context: 'This is the Google Apps Script implementation of the Sheets-to-Clay connection; a separate project below uses Make and HTTP automation.',
    workflow: ['Read or prepare data in Google Sheets.', 'Use Apps Script to format and send the relevant record through a webhook.', 'Pass the data to the Clay table workflow.'],
    stack: ['Google Sheets', 'Google Apps Script', 'Clay', 'Webhooks'],
  },
  {
    slug: 'gohighlevel-lead-generation-sales',
    title: 'GoHighLevel Lead Generation & Sales Automation — LinkedIn Outreach, CRM Pipelines, Appointment Scheduling & Email Workflows',
    shortTitle: 'GoHighLevel Lead Generation and Sales Automation',
    category: 'automations',
    summary: 'Brings outreach, lead pipeline stages, appointments and follow-up email into a GoHighLevel sales workflow.',
    context: 'The project connects lead generation activity to CRM pipeline management and the subsequent scheduling and email steps.',
    workflow: ['Bring LinkedIn outreach activity into the lead-generation process.', 'Organize leads and stages in GoHighLevel CRM pipelines.', 'Coordinate appointment scheduling and email follow-up.'],
    stack: ['GoHighLevel', 'LinkedIn', 'CRM pipelines', 'Email automation'],
  },
  {
    slug: 'youtube-liked-videos-ifttt-sheets',
    title: 'YouTube Liked Video Tracking Automation — IFTTT & Google Sheets Data Logging',
    shortTitle: 'YouTube Liked Video Tracking with IFTTT',
    category: 'automations',
    summary: 'Logs liked YouTube videos to Google Sheets with an IFTTT automation.',
    context: 'A small personal-data logging workflow replaces manual copying of liked-video information into a spreadsheet.',
    workflow: ['Use a liked YouTube video as the automation event.', 'Pass the event information through IFTTT.', 'Record the video information in Google Sheets.'],
    stack: ['IFTTT', 'YouTube', 'Google Sheets'],
  },
  {
    slug: 'facebook-content-marketing-make',
    title: 'Facebook Content Marketing Automation — Make.com, Google Sheets, Mailchimp & Google Calendar Integration',
    shortTitle: 'Facebook Content Marketing Automation',
    category: 'automations',
    summary: 'Coordinates Facebook content planning and email marketing data across Sheets, Mailchimp and Calendar.',
    context: 'The workflow brings together content inputs, scheduling information and email marketing tools rather than managing each step in isolation.',
    workflow: ['Organize campaign or content information in Google Sheets.', 'Use Make to connect Facebook-related activity with Google Calendar.', 'Coordinate the connected email-marketing step in Mailchimp.'],
    stack: ['Make', 'Facebook', 'Google Sheets', 'Mailchimp', 'Google Calendar'],
  },
  {
    slug: 'hotel-booking-operations-make',
    title: 'Hotel Booking Operations Automation — Make.com, Jotform, Airtable, Google Sheets, Asana & ActiveCampaign',
    shortTitle: 'Hotel Booking Operations Automation',
    category: 'automations',
    summary: 'Connects booking form intake with records, task management and email follow-up tools.',
    context: 'Hotel booking information passes between the intake form, operational records, team tasks and marketing or guest communication tools.',
    workflow: ['Collect booking details through Jotform.', 'Organize the data in Airtable and Google Sheets with Make.', 'Connect operational tasks in Asana and communication steps in ActiveCampaign.'],
    stack: ['Make', 'Jotform', 'Airtable', 'Google Sheets', 'Asana', 'ActiveCampaign'],
  },
  {
    slug: 'google-sheets-clay-make-http',
    title: 'Google Sheets-to-Clay Lead Data Integration — Make.com & HTTP Automation',
    shortTitle: 'Google Sheets to Clay with Make and HTTP',
    category: 'integrations',
    summary: 'A separate Sheets-to-Clay lead data workflow built with Make and HTTP requests.',
    context: 'This implementation uses Make and HTTP automation for the Sheets-to-Clay connection, distinct from the Apps Script and webhook project.',
    workflow: ['Take lead data from Google Sheets.', 'Use Make to prepare and send the data through an HTTP step.', 'Connect the result with the Clay table workflow.'],
    stack: ['Make', 'HTTP', 'Google Sheets', 'Clay'],
  },
  {
    slug: 'it-ticket-notifications-make-twilio',
    title: 'IT Support Ticket Notification Automation — Make.com, monday.com, Airtable & Twilio',
    shortTitle: 'IT Ticket Notifications with Make and Twilio',
    category: 'integrations',
    summary: 'Links IT ticket records and status information with automated notifications.',
    context: 'The project connects work tracking and ticket data with an outbound notification channel for support operations.',
    workflow: ['Use monday.com and Airtable for ticket-related information.', 'Connect the records and workflow steps through Make.', 'Send the related notification through Twilio.'],
    stack: ['Make', 'monday.com', 'Airtable', 'Twilio'],
  },
  {
    slug: 'hubspot-contact-gmail-n8n',
    title: 'HubSpot Contact Management & Gmail Notification Automation — n8n, Jotform & Google Sheets Integration',
    shortTitle: 'HubSpot Contact Management and Gmail Notifications',
    category: 'integrations',
    summary: 'Moves contact-form information through an n8n and HubSpot workflow with Gmail notifications.',
    context: 'The workflow combines a form submission, structured contact information and an email notification in one connected process.',
    workflow: ['Capture contact information through Jotform.', 'Process the information with n8n, Google Sheets and HubSpot.', 'Send the relevant notification through Gmail.'],
    stack: ['n8n', 'HubSpot', 'Jotform', 'Google Sheets', 'Gmail'],
  },
  {
    slug: 'pdf-invoice-pabbly-google-workspace',
    title: 'Automated PDF Invoice Generation & Email Delivery — Pabbly Connect & Google Workspace Business Process Automation',
    shortTitle: 'PDF Invoice Generation with Pabbly and Google Workspace',
    category: 'automations',
    summary: 'Uses form and document data to prepare PDF invoices and send them by email through a connected Google Workspace process.',
    context: 'This workflow reduces manual copying between intake, document creation, file storage and invoice delivery.',
    workflow: ['Take invoice inputs from Google Forms and the supporting lookup data.', 'Use Pabbly Connect, Google Docs and Drive to prepare and store a PDF invoice.', 'Send the resulting invoice through Gmail.'],
    stack: ['Pabbly Connect', 'Google Forms', 'Google Docs', 'Google Drive', 'Gmail'],
  },
  {
    slug: 'quickbooks-invoice-webhook-platform',
    title: 'QuickBooks Invoice Digitization & Webhook Automation Platform — React, Node.js, MongoDB & AWS S3',
    shortTitle: 'QuickBooks Invoice Webhook Platform',
    category: 'webhooks',
    summary: 'A custom application for moving QuickBooks invoice information into a connected platform through webhooks.',
    context: 'The project combines a React interface, Node.js backend, database and file storage with an invoice event workflow.',
    workflow: ['Receive QuickBooks Enterprise cloud invoice information through a webhook flow.', 'Process and store the invoice data in the Node.js and MongoDB application.', 'Use the React interface and AWS S3-backed file handling in the connected platform.'],
    stack: ['React', 'Node.js', 'MongoDB', 'AWS S3', 'QuickBooks', 'Webhooks'],
  },
  {
    slug: 'slack-response-tracking-zapier',
    title: 'Slack Response Tracking & Google Sheets Automation — Zapier Workflow Integration',
    shortTitle: 'Slack Response Tracking with Zapier',
    category: 'automations',
    summary: 'Tracks Slack responses in Google Sheets using a Zapier workflow.',
    context: 'The project turns response activity in a team communication channel into structured spreadsheet records.',
    workflow: ['Observe the relevant Slack response activity.', 'Use Zapier to carry the response information between apps.', 'Record the tracking data in Google Sheets.'],
    stack: ['Zapier', 'Slack', 'Google Sheets'],
  },
  {
    slug: 'ai-support-tickets-n8n-hubspot',
    title: 'AI-Powered Automated Support Ticket Management — n8n, HubSpot, OpenAI, Notion & Jotform',
    shortTitle: 'AI Support Ticket Management',
    category: 'ai-automations',
    summary: 'Routes support form submissions through an AI-assisted ticket workflow across HubSpot and Notion.',
    context: 'The workflow connects request intake and AI processing with the systems used to track support work and related information.',
    workflow: ['Capture a support request through Jotform.', 'Use n8n and OpenAI within the ticket management workflow.', 'Connect the resulting work to HubSpot and Notion.'],
    stack: ['n8n', 'HubSpot', 'OpenAI', 'Notion', 'Jotform'],
  },
  {
    slug: 'jira-service-management-ticket-automation',
    title: 'Jira Service Management IT Support & Ticket Workflow Automation',
    shortTitle: 'Jira Service Management Ticket Automation',
    category: 'automations',
    summary: 'Automates steps in an IT support ticket workflow using Jira Service Management.',
    context: 'This project focuses on repeatable support-ticket handling within Jira Service Management.',
    workflow: ['Capture or organize incoming IT support tickets.', 'Apply ticket workflow rules in Jira Service Management.', 'Coordinate status changes and the subsequent support steps.'],
    stack: ['Jira Service Management', 'IT support automation'],
  },
  {
    slug: 'twitter-x-profile-scraper-python-selenium',
    title: 'Twitter/X Profile Data Scraping Platform — Python, Selenium & Web Automation',
    shortTitle: 'Twitter/X Profile Scraper with Python and Selenium',
    category: 'data-scraping',
    summary: 'A web form takes a designation and location, then Python and Selenium gather matching profile information for spreadsheet export.',
    context: 'The demonstrated application provides a search form so a user can look for profiles by professional designation and location without editing the scraper code.',
    workflow: ['Enter a designation and location in the web form.', 'Run the search and browser interaction through Python and Selenium.', 'Extract profile names and URLs into a spreadsheet-compatible output.'],
    stack: ['Python', 'Selenium', 'Twitter/X', 'Spreadsheet export'],
    note: 'The supplied demonstration shows the form, browser automation and Excel-compatible results. It does not establish unrestricted access to the platform.',
  },
  {
    slug: 'linkedin-profile-research-ai-agent',
    title: 'LinkedIn Profile Scraping AI Agent — n8n, OpenAI, Google Sheets & Window Buffer Memory',
    shortTitle: 'LinkedIn Profile Research AI Agent',
    category: 'data-scraping',
    summary: 'A conversational research agent uses a LinkedIn profiles tool and session memory to handle follow-up requests.',
    context: 'The demonstrated n8n agent combines an OpenAI chat model, a LinkedIn profiles tool and Window Buffer Memory for conversational professional-profile research.',
    workflow: ['Submit a natural-language request to the n8n chat trigger.', 'Let the agent call the profiles tool while keeping the session context in memory.', 'Return the research response and use Google Sheets in the structured-data workflow.'],
    stack: ['n8n', 'OpenAI', 'LinkedIn profiles tool', 'Google Sheets', 'Window Buffer Memory'],
    note: 'The supplied recording does not establish direct LinkedIn API integration, automated outreach or extraction of private contact information.',
  },
  {
    slug: 'square-dashboard-retail-automation',
    title: 'Square Dashboard Inventory, Purchase Order & Sales Automation — Python, Google Apps Script & Google Sheets',
    shortTitle: 'Square Inventory, Purchase Order and Sales Automation',
    category: 'automations',
    summary: 'Coordinates Square catalog exports, purchase-order status processing and sales reports with Python and spreadsheet automation.',
    context: 'The documented system uses Python scripts for Square browser and file operations, with Google Apps Script handling spreadsheet-native transformations.',
    workflow: ['Export and process Square catalog information for Google Sheets.', 'Check purchase-order states and move completed records into historical sheets.', 'Export Square sales details for a selected period and refresh reporting sheets.'],
    stack: ['Square Dashboard', 'Python', 'Google Apps Script', 'Google Sheets', 'CSV'],
    note: 'The supplied documentation describes browser, file and spreadsheet automation; it does not establish a Square API integration or real-time synchronization.',
  },
  {
    slug: 'hcpa-pipedrive-automation-architecture',
    title: 'HCPA Business Process Automation & Pipedrive CRM Architecture — Pipedrive, Zapier, Make.com, Google Ads, Meta & Marketing Automation',
    shortTitle: 'HCPA Pipedrive CRM and Automation Architecture',
    category: 'solution-architecture',
    summary: 'A cross-department process review and Pipedrive-centered automation roadmap covering sales, marketing and operations.',
    context: 'The work analyzed existing processes and mapped opportunities to connect lead management, marketing, documents, reporting and finance around Pipedrive.',
    workflow: ['Review operational workflows and identify repetitive work or handoff gaps.', 'Design a Pipedrive-centered CRM structure with pipelines, fields and workflow triggers.', 'Document a roadmap for potential Zapier, Make, advertising, reporting and finance integrations.'],
    stack: ['Pipedrive', 'Zapier', 'Make', 'Google Ads', 'Meta', 'CRM architecture'],
    note: 'This is business process analysis and solution architecture. The source document proposes many integrations; it does not establish that every proposed connection was deployed.',
  },
];

export const projectsBySlug: Record<string, Project> = Object.fromEntries(projects.map(project => [project.slug, project]));
export const projectPath = (slug: string) => `/case-studies/${slug}/`;
