import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { ArrowUpRight, Check, Phone, CalendarDays, UserRoundCheck } from 'lucide-react';
import { SiteHeader,SiteFooter,AssessmentLink } from '../../site-components';
const industries:Record<string,{name:string;title:string;intro:string;pain:string;uses:string[];cta:string}>={
 hvac:{name:'HVAC',title:'Every missed HVAC call is a customer who can call the next company.',intro:'Capture service enquiries, identify the job type and urgency, follow up and give your dispatch team a clear next step when technicians are busy.',pain:'When everyone is on a job, the phone still rings. A missed service request can disappear before anyone calls back.',uses:['After-hours call capture','Service and location qualification','Appointment requests','Estimate follow-up'],cta:'See my HVAC automation plan'},
 roofing:{name:'ROOFING',title:'Your sales team shouldn’t have to chase every roofing lead manually.',intro:'Respond to estimate requests, collect project details, organize appointments and keep follow-up moving while your team works on site.',pain:'A web form or missed call creates an opportunity only if the next response happens quickly and gets recorded.',uses:['New lead response','Project qualification','Estimate reminders','CRM updates'],cta:'Map my roofing lead workflow'},
 plumbing:{name:'PLUMBING',title:'When the phone rings during a job, your customer shouldn’t hear silence.',intro:'Capture the service need, location and urgency, then route defined calls or trigger follow-up while your plumbers are in the field.',pain:'Emergency and routine requests need different next steps. A one-size-fits-all voicemail gives neither one enough context.',uses:['Call handling','Urgency routing','Service request capture','Appointment follow-up'],cta:'See my plumbing call plan'},
 'home-services':{name:'HOME SERVICES',title:'Your technicians are doing their jobs. Let the first response keep moving.',intro:'For HVAC, roofing, plumbing, electrical, cleaning and other field teams: capture enquiries, qualify the work and give your office the context to act.',pain:'A busy crew should not have to choose between finishing a job and answering every new enquiry in real time.',uses:['Missed calls','Lead qualification','Booking requests','CRM and team updates'],cta:'Map my home-services workflow'},
};
export function generateStaticParams(){return Object.keys(industries).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=industries[slug];return {title:`AI Automation for ${p?.name||'Home Services'}`,description:p?.intro}}
export default async function Industry({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=industries[slug];if(!p)notFound();return <><SiteHeader/><main><section className="wrap industry-hero"><div><p className="eyebrow">AI AUTOMATION FOR {p.name}</p><h1>{p.title}</h1><p>{p.intro}</p><AssessmentLink>{p.cta} <ArrowUpRight size={18}/></AssessmentLink></div><div className="industry-visual" aria-label="Illustrative service enquiry workflow"><span>WHEN YOUR TEAM IS BUSY</span><div><Phone size={24}/><strong>New customer enquiry</strong><small>Call or website form</small></div><div><UserRoundCheck size={24}/><strong>Details captured</strong><small>Service · location · urgency</small></div><div><CalendarDays size={24}/><strong>Next step routed</strong><small>Team receives the context</small></div></div></section><section className="offer-problem"><div className="wrap offer-problem-inner"><p className="eyebrow">THE COST OF A SLOW HANDOFF</p><h2>{p.pain}</h2></div></section><section className="wrap interior-section"><div className="section-intro"><p className="eyebrow">WHERE TO START</p><h2>One call or lead type.<br/><em>One clear next step.</em></h2></div><div className="industry-uses">{p.uses.map((use,i)=><div key={use}><span>0{i+1}</span><h3>{use}</h3><Check size={18}/></div>)}</div><div className="interior-banner"><h2>What happens when a customer reaches out and no one is free?</h2><p>Tell me your current process and I’ll map where an automation could help.</p><AssessmentLink light>{p.cta} <ArrowUpRight size={18}/></AssessmentLink></div></section></main><SiteFooter/></>}
